"""Install a spec-built plugin into the game's Data folder, with guards and a backup.

    .venv/bin/python install_plugin.py projects/coolworld.spec.json [--allow-replace-foreign REASON]

Same logic as the geck_plugin_install MCP tool (geck_mcp/authoring.py). Refuses when the
build does not match its receipt, GECK has the plugin open with unsaved changes, the
installed file is not generated by this project (unless a reason is given), or it was
edited since the last install. Every replaced file is backed up in state/backups/.
"""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
from geck_mcp.authoring import Authoring, AuthoringError  # noqa: E402
from geck_mcp.config import Project  # noqa: E402
from geck_mcp.esp import build as builder  # noqa: E402
from geck_mcp.service import Service  # noqa: E402


def editor_title(project):
    try:
        service = Service(project)
        try:
            result = service.status()
        finally:
            service.close()
        return result['data']['editorTitle'] if result['ok'] else None
    except Exception:
        return None     # GECK not running: installing is safe


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('spec', type=Path)
    parser.add_argument('--project-config', type=Path)
    parser.add_argument('--allow-replace-foreign', metavar='REASON')
    args = parser.parse_args()
    spec = builder.load_spec(args.spec.read_text())
    project = Project.load(args.project_config or ROOT / 'projects' / (spec['project_id'] + '.json'))
    try:
        entry = Authoring(project, spec_path=args.spec).install(editor_title(project), args.allow_replace_foreign)
    except AuthoringError as error:
        print(json.dumps({'ok': False, 'code': error.code, 'error': str(error)}))
        return 2
    print(json.dumps(dict(entry, ok=True)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
